name = "email-worker"
type = "javascript"
main = "index.js"

compatibility_date = "2024-01-01"
workers_dev = true

# D1数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "temp_email_db"
database_id = "0a1989cd-6f62-4aed-a6d1-31801c927c2c"

[vars]
WORKER_URL = "https://email-worker.2668812066.workers.dev"
EMAIL_DOMAIN = "220901.xyz"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"

[triggers]
crons = ["0 0 * * *"] # Clean up expired emails every 24 hours