name = "email-worker"
type = "javascript"
main = "index.js"

compatibility_date = "2024-01-01"
workers_dev = true

# KV Namespace binding
kv_namespaces = [
  { binding = "temp-email", id = "24945969b1da45bc80a18e4acdf94e9a" }
]


[vars]
WORKER_URL = "https://email-worker.2668812066.workers.dev"
EMAIL_DOMAIN = "220901.xyz"


[build]
command = "npm run build"

[build.upload]
format = "service-worker"

[triggers]
crons = ["0 */8 * * *"] # Clean up expired emails every 8 hours