name = "email-worker"
type = "javascript"
main = "index.js"

compatibility_date = "2024-01-01"
workers_dev = true

# D1数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "temp_email_db"
database_id = "228e475ca9d5465f93fc5103eb0f1f96"

[vars]
WORKER_URL = "https://email-worker.candlespark.workers.dev"
EMAIL_DOMAIN = "147586.xyz"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"

[triggers]
crons = ["0 0 * * *"] # Clean up expired emails every 24 hours