name = "email-routing-worker"
main = "index.js"

compatibility_date = "2024-01-01"
workers_dev = true

# D1数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "temp_email_db"
database_id = "0a1989cd-6f62-4aed-a6d1-31801c927c2c"

[build]
command = "npm run build" 