name = "email-routing-worker"
type = "javascript"
main = "index.js"

compatibility_date = "2024-01-01"
workers_dev = true

[build]
command = "npm run build"

[build.upload]
format = "service-worker"

# Email routing rules
[[email_routing]]
pattern = "*@temp-email.2668812066.workers.dev"
action = "forward"
destination = "email-worker"